### ISSUE TITLE
Not an issue, are you slose1?

### ISSUE THREAD

**Issue by perez987** [slosepxls/B460M-aorus-elite-opencore#1]
@slosepxls 
Good morning, I'm sorry to read that the site has been hacked.
I was surprised that I can't access it throughout the morning but now I understand what may have happened. What a disappointment!

I am perez987, I based my text [UEFI Secure Boot and OpenCore: the easy way](https://github.com/perez987/OpenCore-and-UEFI-Secure-Boot/blob/main/guide/The%20easy%20way.md) on your post.

I hope you can repair the damage as soon as possible. When you're done, I'll change the current slose1 link to the new repo with the new name.

**Comment by slosepxls** [comment]
yes.. hacked
